version = "1.3.*"
upstream_repository = "https://github.com/TaylorSMarks/playsound"

[tool.stubtest]
ignore_missing_stub = true
# TODO: Does not compile with Python 3.12 as of 2024-10-18 (release 1.3.0).
skip = true
