version = "2.49.*"
upstream_repository = "https://github.com/boto/boto"
requires = []
partial_stub = true

[tool.stubtest]
ignore_missing_stub = true
# TODO: Does not import with Python 3.12 as of 2024-10-18 (release 2.49.0).
skip = true
